### ISSUE TITLE
Use redis-server for login sessions

### ISSUE THREAD

**Issue by mimen** [smart-garden/server#15]

**Comment by tmgriffith** [comment]
so im pretty sure I got the sessions up and working. github wont let me do a pull req to master from erik-branch though. 

I used @mimen 's and @kmannislands SCLibrary as a reference and implemented redis with two new files "checkLoggedIn" and "checkLoggedOut". I tested to see if you could bypass the login by entering a url in the address bar and it now redirects back to login if it does not find a login cookie present. and after you login, it does not redirect to login for every request as long as the cookie is valid. 

Please look it over and let me know if you encounter any problems with it. And if it is good, help me figure out how to get it on the master branch.
